version: "3.7"

services:

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    volumes:
      - ./minio/data:/data
    environment:
      - MINIO_ACCESS_KEY=TESTKEY
      - MINIO_SECRET_KEY=TESTSECRET
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 35s
      timeout: 20s
      retries: 3
    command: server --compat /data

  localstack:
    image: localstack/localstack:0.11.1
    ports:
      - '4569:4569'
      - '4576:4576'
    environment:
      - SERVICES=dynamodb,sqs

  redis:
    image: redis
    ports:
      - 6379:6379